Biometrika.Manager.CI/Biometrika.Manager.CI/Controllers/CertificationController.cs
using BCR.Bio.Domain;
using BCR.Bio.Domain.NV;
using BCR.Bio.Domain.NV.DTO;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebNV.Models.NV;
using BCR.System.Log;
using System.Net.Http.Headers;

namespace WebNV.Controllers
{
    [Authorize]
    public class CertificationController : BaseController
    {

        public ActionResult Find(CITxModel cITxModel, int idPaginacion = 0, bool isCertification = true)
        {
            if (cITxModel.FilterParams is null)
            {
                cITxModel.FilterParams = new CITxDTO
                {
                    ReceiptId = 0,
                    TypeId = BCR.Bio.Domain.NV.DTO.TypeId.RUT,
                    ValueId = "",
                    TrackId = "",
                    Type = isCertification ? 0 : 1
                };
            }

            Log4Bio.Info("Cargando vista Certification/Find receiptId: " + cITxModel.FilterParams.ReceiptId + " typeId: " + cITxModel.FilterParams.TypeId + " valueId: " + cITxModel.FilterParams.ValueId + " trackId: " + cITxModel.FilterParams.TrackId);
            if (!cITxModel.FilterParams.EventTimeFrom.HasValue || cITxModel.FilterParams.EventTimeFrom == DateTime.MinValue) cITxModel.FilterParams.EventTimeFrom = DateTime.Now.AddDays(-3);
            if (!cITxModel.FilterParams.EventTimeTo.HasValue || cITxModel.FilterParams.EventTimeTo == DateTime.MinValue) cITxModel.FilterParams.EventTimeTo = DateTime.Now;

            int companyId;
            if (User.IsInRole("Super Admin") && cITxModel.CompanyId > 0)
            {
                Log4Bio.Info("Es Super Admin y revisa Company : " + cITxModel.CompanyId);
                companyId = cITxModel.CompanyId;
            }
            else
            {
                Log4Bio.Info("No es Super Admin, se selecciona la Company del usuario: " + CurrentUserCompany.Id);
                companyId = CurrentUserCompany.Id;
            }

            cITxModel.FilterParams.CompanyId = companyId;
            Log4Bio.Info("Buscando resultados desde " + cITxModel.FilterParams.EventTimeFrom + " hasta " + cITxModel.FilterParams.EventTimeTo);
            cITxModel.FilterParams.Paginacion = new Paginacion()
            {
                Cantidad = 10,
                Pagina = idPaginacion
            };

            cITxModel.List = UoW.CITxService.ListDTOByCriteria(cITxModel.FilterParams);

            ViewBag.CompanyList = new List<SelectListItem>();

            if (User.IsInRole("Super Admin"))
            {
                Log4Bio.Info("SuperAdmin: cargando lista de compañías");
                var companies = UoW.CompanyService.List();
                foreach (var icompany in companies)
                {
                    ViewBag.CompanyList.Add(new SelectListItem { Text = icompany.Name, Value = icompany.Id.ToString() });
                }
            }
            if (isCertification)
                return View(cITxModel);
            else
                return View("FindProcedures", cITxModel);
        }

        [HttpGet]
        public ActionResult FindProcedures()
        {
            return Find(new CITxModel(), 0, false);
        }

        [HttpPost]
        public ActionResult Detail(int certId)
        {
            Log4Bio.Info("Cargando vista detalle de Certificación para el ID: " + certId);
            CITx model = UoW.CITxService.GetById(certId);
            model.Score = ParseScore(model.Score);
            return View(model);
        }


        string ParseScore(string scoreString)
        {
            if (!string.IsNullOrEmpty(scoreString))
            {
                scoreString = scoreString.Replace('.', ',');
                double score = double.Parse(scoreString);
                Log4Bio.Info("Score: " + scoreString + " Formateado :" + score.ToString("F") + "%");
                return score.ToString("F") + "%";
            }
            Log4Bio.Info("Score vacío");
            return "";
        }

        [HttpPost]
        public FileResult DownloadPDF(int certId)
        {
            Log4Bio.Info("DownloadPDF con ID: " + certId);
            CITx certification = UoW.CITxService.GetById(certId);

            if (!string.IsNullOrEmpty(certification.CertifyPdf))
            {
                Log4Bio.Info("PDF encontrado se genera descarga.");
                var stream = Convert.FromBase64String(certification.CertifyPdf);
                return File(stream, "application/pdf", "Certificacion_" + certId + ".pdf");
            }
            else
            {
                Log4Bio.Error("PDF no encontrado. certId:" + certId);
                return null;
            }
        }

        [HttpPost]
        public FileResult DownloadRecibo(int receiptIdXml)
        {
            Log4Bio.Info("DownloadRecibo con receiptIdXml: " + receiptIdXml);
            Recibo recibo = UoW.ReciboService.GetById(receiptIdXml);

            if (!string.IsNullOrEmpty(recibo.ReciboXml))
            {
                Log4Bio.Info("'XML encontrado se genera descarga.");
                var stream = new System.IO.MemoryStream(System.Text.Encoding.UTF8.GetBytes(recibo.ReciboXml));
                return File(stream, "application/octet-stream", "Recibo_" + receiptIdXml + ".xml");
            }
            else
            {
                Log4Bio.Error("XML no encontrado. receiptIdXml:" + receiptIdXml);
                return null;
            }
        }

        //[Authorize(Roles = ("Super Admin, Administrador, Operador"))]
        //public ActionResult New()
        //{
        //    Log4Bio.Info("Cargando vista New Certification");
        //    CertificationModel certificationModel = new CertificationModel();
        //    Config config = UoW.ConfigService.GetByCompanyId(CurrentUserCompany.Id);
        //    if (config is null)
        //    {
        //        Log4Bio.Info("No se encuentra Config de la compañía en la BBDD. Se procede a crear una nueva.");
        //        Company company = (Company)CurrentUserCompany;
        //        config = new Config(company);
        //        config.Id = UoW.ConfigService.Create(config);
        //    }
        //    config = UoW.ConfigService.GetById(config.Id);
        //    Log4Bio.Info("Cargamos la configuración de la compañía para lanzar la vista");
        //    certificationModel.ReceiverEmail = config.ReceiverEmails;
        //    //certificationModel.OnBoarding = config.ForceOnBoarding;
        //    return View(certificationModel);
        //}


        [Authorize(Roles = ("Super Admin, Administrador, Operador"))]
        public ActionResult New()
        {
            Log4Bio.Info("Cargando vista New Certification");
            CertificationModel certificationModel = new CertificationModel();
            CompanyWorkFlow companyWorkFlow = UoW.CompanyWorkFlowService.GetByCompanyId(CurrentUserCompany.Id);
            if (companyWorkFlow is null)
            {
                Company company = (Company)CurrentUserCompany;
                companyWorkFlow = new CompanyWorkFlow(company);
                companyWorkFlow.Id = UoW.CompanyWorkFlowService.Create(companyWorkFlow);

            }
            companyWorkFlow = UoW.CompanyWorkFlowService.GetById(companyWorkFlow.Id);
            Log4Bio.Info("Cargamos la configuración de la compañía para lanzar la vista");
            certificationModel.ReceiverEmail = companyWorkFlow.ReceiverList;
            return View(certificationModel);
        }



        [HttpPost]
        [Authorize(Roles = ("Super Admin, Administrador, Operador"))]
        public ActionResult New(CertificationModel certificationModel)
        {
            Log4Bio.Info("Post New Certification: " + certificationModel.TypeId + " " + certificationModel.ValueId);
            Log4Bio.Info("ReceiverEmail: " + certificationModel.ReceiverEmail + ", Email: " + certificationModel.Email + ", Phone: " + certificationModel.Phone);
            ResponseCreateTx response = CreateTx(certificationModel);
            if (!string.IsNullOrEmpty(response.Message) && response.Message.Contains("Rut Inválido"))
            {
                Log4Bio.Error("Error al crear Nueva Certificación Rut Inválido :" + certificationModel.ValueId);
                return View(certificationModel);
            }
            return View("Response", response);
        }


        //private ResponseCreateTx CreateTx(CertificationModel certificationModel)
        //{

        //    if (!ValidateRut(certificationModel.ValueId)) return new ResponseCreateTx
        //    {
        //        Message = "Rut Inválido"
        //    };
        //    Config config = UoW.ConfigService.GetByCompanyId(CurrentUserCompany.Id);
        //    int company = int.Parse(ConfigurationManager.AppSettings["Company"]);
        //    string guid = Guid.NewGuid().ToString("N");
        //    int application = int.Parse(ConfigurationManager.AppSettings["Application"]);
        //    string theme = ConfigurationManager.AppSettings["Theme"];
        //    string type = ConfigurationManager.AppSettings["Type"];
        //    int signerInclude = int.Parse(ConfigurationManager.AppSettings["SignerInclude"]);
        //    int checklockSrcei = int.Parse(ConfigurationManager.AppSettings["ChecklockSrcei"]);
        //    string[] listMailsDestinatary;
        //    string currentAction = "ciweb/ciCreateTx";
        //    string callbackUrl = ConfigurationManager.AppSettings["CallbackUrl"];
        //    string redirectUrl = ConfigurationManager.AppSettings["Redirecturl"];
        //    string uri = ConfigurationManager.AppSettings["ApiUrl"] + currentAction;

        //    try
        //    {
        //        listMailsDestinatary = certificationModel.ReceiverEmail.Split(',');
        //    }
        //    catch (Exception ex)
        //    {
        //        listMailsDestinatary = certificationModel.ReceiverEmail.Split(';');

Biometrika.Manager.CI/Biometrika.Manager.CI/Views/Certification/New.cshtml
@model WebNV.Models.NV.CertificationModel

@{

    ViewBag.Title = "Nueva Certificación";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="container">
    <div class="card">
        <h5 class="card-header text-white">Nueva Certificación</h5>
        <div class="card-body">
            <h5 class="card-title">Completa los datos para comenzar el proceso de certificación.</h5>
            @using (Html.BeginForm("New", "Certification", FormMethod.Post, new { role = "form", id = "newForm", name = "newForm" }))
            {

                <div class="form-row align-items-center">
                    <div class="col-sm-12 col-md-2">
                        @Html.EnumDropDownListFor(m => m.TypeId, new { @class = "form-control" })
                    </div>
                    <div class="col-sm-12 col-md-2">
                        @*@Html.Label("Nº Documento", new { @class = "control-label" })*@
                        @Html.TextBoxFor(m => m.ValueId, new { @class = "form-control", placeholder = "12345678-K", style = "text-transform: uppercase" })
                        @Html.ValidationMessageFor(m => m.ValueId)
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <div class="form-group">
                            <div class="form-group">
                                @Html.Label("Email", new { @class = "control-label" })
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-3">
                        <div class="form-group">
                            @Html.Label("Teléfono", new { @class = "control-label", placeholder = "912345678" })
                            @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
                        </div>
                    </div>
                    @*<div class="col-sm-12 col-md-4">
                            <div class="form-group">
                                @Html.Label("Forzar OnBoarding", new { @class = "control-label" })
                                @Html.CheckBoxFor(m => m.OnBoarding, new { @class = "form-control" })
                            </div>
                        </div>*@
                    <div class="col-sm-12">
                        <div class="form-group">
                            @Html.Label("Email Receptor(es) Separados por coma", new { @class = "control-label" })
                            @Html.EditorFor(m => m.ReceiverEmail, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <button type="submit" id="btn-new-cert" class="btn btn-lg btn-primary" style="margin-top:20px;">
                                <i class="glyphicon glyphicon-plus-sign"></i> Iniciar Nueva Certificación
                            </button>                            
                            <span id="loading-img" hidden>
                                <img style="width:5%" src="~/Images/loading.gif" />
                            </span>
                        </div>
                    </div>
                </div>



            }
        </div>
    </div>
</div>
<script>
    var urlBpClient = 'http://localhost:9191';

    function CollectData() {
        // Instanciamos BiometrikaClient con la URL de consumo de la aplicación
        var biometrikaClient = new BiometrikaClient(urlBpClient);
        // Seteamos las propiedades requeridas
        biometrikaClient.TypeId = $("#TipoId").val().trim();
        biometrikaClient.ValueId = $("#ValueId").val().trim();

        biometrikaClient.TokenContent = '0';

    }

    $(function () {

        $('#Phone').val('');
        $('#Phone').prop('placeholder', '912345678');
        $('#Email').prop('placeholder', 'destinatario@correo.com');
        $.validator.addMethod("validRut", function (value, element, params) {
            return ValidateRut(this.value);
        }, "* Rut inválido");

        jQuery.validator.unobtrusive.adapters.add('chileanrut', {}, function (options) {
            options.rules['validRut'] = true;
            options.messages['validRut'] = options.message;
        });

        $("#newForm").validate({
            rules: {
                ValueId: {
                    validRut: true,
                    required: true,
                },

            },
        });

        $('#newForm').submit(function () {
            if ($(this).valid()) {
                ShowLoading();
            }
        });

    });

    function ShowLoading() {
            $("#loading-img").removeAttr('hidden');
            $("#btn-new-cert").prop('disabled', true);
    };

    function ValidateRut(rut) {
        rut = rut.trim();

        var isValid = false;

        // type check
        if (!rut || !rut.length || typeof rut !== 'string') {
            return isValid;
        }

        var regex = new RegExp('^([0-9]+-[0-9kK])$');
        if (!regex.test(rut)) {
            return isValid;
        }

        var rutAux = rut.split("-")[0];
        var dv = rut.split("-")[1].toUpperCase();
        var secuencia = [2, 3, 4, 5, 6, 7, 2, 3];
        var sum = 0;
        for (var i = rutAux.length - 1; i >= 0; i--) {
            var d = rutAux.charAt(i)
            sum += new Number(d) * secuencia[rutAux.length - (i + 1)];
        };
        // sum mod 11
        var rest = 11 - (sum % 11);
        // si es 11, retorna 0, sino si es 10 retorna K,
        // en caso contrario retorna el numero
        var resultado = rest === 11 ? '0' : rest === 10 ? 'K' : rest.toString();

        if (resultado === dv) {
            isValid = true;
        }

        return isValid;
    }
</script>

Biometrika.Manager.CI/Biometrika.Manager.CI/Views/Certification/Response.cshtml
@model BCR.Bio.Domain.ResponseCreateTx

@{
    /**/

    ViewBag.Title = "Respuesta Certificación";
    Layout = "~/Views/Shared/_Layout.cshtml";

}


<div class="container">
    <div class="card">
        <h5 class="card-header text-white">Resultados Ingreso Certificación</h5>
        <div class="card-body">
            @if (Model != null && !string.IsNullOrEmpty(Model.Trackid))
            {
                <h3>Solicitud enviada exitosamente</h3>
                <p>Se ha enviado un correo electrónico con la dirección para realizar la certificación, de todas formas si quieres puedes copiar el enlace de abajo y enviarlo a tu contacto</p>
                <div class="lead">
                    <ul>
                        @if (!string.IsNullOrEmpty(Model.Trackid))
                        {
                            <li>
                                Id Transacción : @Model.Trackid
                            </li>
                        }
                        @if (!string.IsNullOrEmpty(Model.Message))
                        {
                            <li>
                                Mensaje : @Model.Message
                            </li>
                        }
                        @if (!string.IsNullOrEmpty(Model.CiwebUrl))
                        {
                            <li>
                                Enlace (Click para copiar):    <div style="display:inline-block; vertical-align:top;">
                                    <button class="url-to-copy btn btn-primary">Copiar Enlace <i class="fa fa-copy"></i></button><br />
                                </div>
                            </li>

                            <li>
                                <div style="display:inline-block; vertical-align:top;">
                                    <a class="btn btn-info" href="@Model.CiwebUrl" target="_blank">Empezar Certificación  <i class="fa fa-external-link-square"></i></a><br />
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            }
            else
            {
                <h3>Ocurrió un error al ingresar la solicitud</h3>
                <p class="lead">Favor verificar las últimas Certificaciones, en caso contrario ingresar una nuevamente.</p>
            }
        </div>

    </div>
</div>


<script>
    var urlToCopy = "@Model.CiwebUrl";

    var copyBtn = document.querySelector('.url-to-copy');

    copyBtn.addEventListener('click', function (event) {
        copyTextToClipboard(urlToCopy);
    });

    function copyTextToClipboard(text) {
        var textArea = document.createElement("textarea");

        textArea.style.position = 'fixed';
        textArea.style.top = 0;
        textArea.style.left = 0;

        textArea.style.width = '2em';
        textArea.style.height = '2em';

        textArea.style.padding = 0;

        // Clean up any borders.
        textArea.style.border = 'none';
        textArea.style.outline = 'none';
        textArea.style.boxShadow = 'none';

        // Avoid flash of white box if rendered for any reason.
        textArea.style.background = 'transparent';


        textArea.value = text;

        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();

        try {
            var successful = document.execCommand('copy');
            var msg = successful ? 'successful' : 'unsuccessful';
            console.log('Copying text command was ' + msg);
            alert('Enlace copiado!');
        } catch (err) {
            console.log('Oops, unable to copy');
        }

        document.body.removeChild(textArea);
    }
</script>