Biometrika.Manager.CI/Biometrika.Manager.CI/Controllers/CompanyWorkFlowController.cs
using BCR.Bio.Domain;
using BCR.Bio.Domain.NV;
using BCR.System.Log;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace WebNV.Controllers
{
    [Authorize(Roles = ("Super Admin"))]
    public class CompanyWorkFlowController : BaseController
    {
        // GET: CompanyWorkFlow
        [HttpGet]
        public ActionResult Index()
        {
            IList<CompanyWorkFlow> workFlows = UoW.CompanyWorkFlowService.GetAll();
            return View(workFlows);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            CompanyWorkFlow companyWorkFlow = UoW.CompanyWorkFlowService.GetById(id);

            string[] parsedAuthorizationMessage = ParseHtml(companyWorkFlow.AuthorizationMessage);

            ViewBag.AuthorizationMessageTitle = parsedAuthorizationMessage[0];
            ViewBag.AuthorizationMessageBody = parsedAuthorizationMessage[1];
            ViewBag.AuthorizationMessageFooter = parsedAuthorizationMessage[2];

            List<SelectListItem> companySelectList = new List<SelectListItem>();

            var companyList = UoW.CompanyService.List();
            foreach (var company in companyList)
            {
                if (companyWorkFlow.Company.Id == company.Id)
                {
                    companySelectList.Add(new SelectListItem() { Value = company.Id.ToString(), Text = company.Name, Selected = true });
                } else
                {
                    companySelectList.Add(new SelectListItem() { Value = company.Id.ToString(), Text = company.Name, Selected = false });
                }
            }
            ViewBag.CompanySelectList = companySelectList;

            //string[] parsedVideoMessage = ParseHtml(companyWorkFlow.VideoMessage);

            //ViewBag.VideoMessageTitle = parsedVideoMessage[0];
            //ViewBag.VideoMessageBody = parsedVideoMessage[1];
            //ViewBag.VideoMessageFooter = parsedVideoMessage[2];


            return View(companyWorkFlow);
        }

        [HttpGet]
        public ActionResult Create()
        {
            CompanyWorkFlow companyWorkFlow = new CompanyWorkFlow();
            List<SelectListItem> companySelectList = new List<SelectListItem>();

            var companyList = UoW.CompanyService.List();
            foreach (var company in companyList)
            {
                companySelectList.Add(new SelectListItem() { Value = company.Id.ToString(), Text = company.Name });
            }
            ViewBag.CompanySelectList = companySelectList;
            return View(companyWorkFlow);
        }

        [HttpPost]
        public ActionResult Create(CompanyWorkFlow formWorkFlow, string AuthorizationMessageFooter, string AuthorizationMessageBody, string AuthorizationMessageTitle, int CompanySelectList)
        {
            string authorizationMessageHtml = GenerateHtml(AuthorizationMessageTitle, AuthorizationMessageBody, AuthorizationMessageFooter);

            try
            {
                Log4Bio.Info("Creando Workflow con id");
                formWorkFlow.AuthorizationMessage = authorizationMessageHtml;
                formWorkFlow.Company = (Company) UoW.CompanyService.GetById(CompanySelectList);
                int id = UoW.CompanyWorkFlowService.Create(formWorkFlow);
                if (id > 0)
                {
                    IList<CompanyWorkFlow> workFlows = UoW.CompanyWorkFlowService.GetAll();
                    return View("Index", workFlows);
                }
                else
                {
                    return View(formWorkFlow);
                }
            }
            catch (Exception ex)
            {
                Log4Bio.Error("Error al crear Workflow");
                Log4Bio.Error(ex.ToString());
                return View(formWorkFlow);
            }
        }

        [HttpGet]
        public ActionResult Clone(int id)
        {
            CompanyWorkFlow baseCompanyWorkFlow = UoW.CompanyWorkFlowService.GetById(id);
            if (baseCompanyWorkFlow != null)
            {
                CompanyWorkFlow newCompanyWorkFlow = new CompanyWorkFlow
                {
                    Authorization = baseCompanyWorkFlow.Authorization,
                    AuthorizationMessage = baseCompanyWorkFlow.AuthorizationMessage,
                    BpWebTypeOnBoarding = baseCompanyWorkFlow.BpWebTypeOnBoarding,
                    BpWebTypeVerify = baseCompanyWorkFlow.BpWebTypeVerify,
                    CheckAdult = baseCompanyWorkFlow.CheckAdult,
                    CheckExpired = baseCompanyWorkFlow.CheckExpired,
                    CheckLockSrcei = baseCompanyWorkFlow.CheckLockSrcei,
                    Company = baseCompanyWorkFlow.Company,
                    GeoRefMandatory = baseCompanyWorkFlow.GeoRefMandatory,
                    Name = baseCompanyWorkFlow.Name + " copia",
                    OnBoardingMandatory = baseCompanyWorkFlow.OnBoardingMandatory,
                    ReceiverList = baseCompanyWorkFlow.ReceiverList,
                    RedirectUrl = baseCompanyWorkFlow.RedirectUrl,
                    SignerInclude = baseCompanyWorkFlow.SignerInclude,
                    Theme = baseCompanyWorkFlow.Theme,
                    Threshold = baseCompanyWorkFlow.Threshold,
                    VideoInclude = baseCompanyWorkFlow.VideoInclude,
                    VideoMessage = baseCompanyWorkFlow.VideoMessage
                };
                UoW.CompanyWorkFlowService.Create(newCompanyWorkFlow);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var res = UoW.CompanyWorkFlowService.Delete<CompanyWorkFlow>(id);
            return Json(new { res }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult Edit(CompanyWorkFlow formWorkFlow, string AuthorizationMessageFooter, string AuthorizationMessageBody, string AuthorizationMessageTitle, int CompanySelectList)
        {
            CompanyWorkFlow companyWorkFlow = UoW.CompanyWorkFlowService.GetById(formWorkFlow.Id);

            string authorizationMessageHtml = GenerateHtml(AuthorizationMessageTitle, AuthorizationMessageBody, AuthorizationMessageFooter);
            //string videoMessageHtml = GenerateHtml(VideoMessageTitle, VideoMessageBody, VideoMessageFooter);

            try
            {
                Log4Bio.Info("Editando Workflow con id :" + companyWorkFlow.Id);
                companyWorkFlow.Name = formWorkFlow.Name;
                companyWorkFlow.Company = (Company) UoW.CompanyService.GetById(CompanySelectList);
                companyWorkFlow.OnBoardingMandatory = formWorkFlow.OnBoardingMandatory;
                companyWorkFlow.BpWebTypeOnBoarding = formWorkFlow.BpWebTypeOnBoarding;
                companyWorkFlow.BpWebTypeVerify = formWorkFlow.BpWebTypeVerify;
                companyWorkFlow.ReceiverList = formWorkFlow.ReceiverList;
                companyWorkFlow.Threshold = formWorkFlow.Threshold;
                companyWorkFlow.Authorization = formWorkFlow.Authorization;
                companyWorkFlow.AuthorizationMessage = authorizationMessageHtml;
                companyWorkFlow.SignerInclude = formWorkFlow.SignerInclude;
                companyWorkFlow.CheckLockSrcei = formWorkFlow.CheckLockSrcei;
                companyWorkFlow.VideoInclude = formWorkFlow.VideoInclude;
                companyWorkFlow.VideoMessage = formWorkFlow.VideoMessage;
                companyWorkFlow.Theme = formWorkFlow.Theme;
                companyWorkFlow.GeoRefMandatory = formWorkFlow.GeoRefMandatory;
                companyWorkFlow.RedirectUrl = formWorkFlow.RedirectUrl;
                companyWorkFlow = UoW.CompanyWorkFlowService.Update(companyWorkFlow);

            }
            catch (Exception ex)
            {
                Log4Bio.Error("Error al editar Workflow");
                Log4Bio.Error(ex.ToString());
            }
            List<SelectListItem> companySelectList = new List<SelectListItem>();

            var companyList = UoW.CompanyService.List();
            foreach (var company in companyList)
            {
                if (companyWorkFlow.Company.Id == company.Id)
                {
                    companySelectList.Add(new SelectListItem() { Value = company.Id.ToString(), Text = company.Name, Selected = true });
                }
                else
                {
                    companySelectList.Add(new SelectListItem() { Value = company.Id.ToString(), Text = company.Name, Selected = false });
                }
            }
            ViewBag.CompanySelectList = companySelectList;
            return View(companyWorkFlow);
        }

        private string GenerateHtml(string title, string body, string footer)
        {
            string separator = "<!-- * -->";
            string htmlGenerated = "<strong>" + title + "</strong> <br />" + separator;
            htmlGenerated += "<p>" + body + "</p> <hr />" + separator;
            htmlGenerated += "<i>" + footer + "</i>";
            return htmlGenerated;
        }


        private string[] ParseHtml(string html)
        {
            string[] separator = { "<!-- * -->" };
            string[] htmlParsed;
            try
            {
                htmlParsed = html.Split(separator, StringSplitOptions.RemoveEmptyEntries);
                if (htmlParsed.Length == 3)
                {
                    string title = htmlParsed[0];
                    title = title.Replace("<strong>", "");
                    title = title.Replace("</strong>", "");
                    title = title.Replace("<br />", "");

                    string body = htmlParsed[1];
                    body = body.Replace("<p>", "");
                    body = body.Replace("</p>", "");
                    body = body.Replace("<hr />", "");

                    string footer = htmlParsed[2];

Biometrika.Manager.CI/Biometrika.Manager.CI/Views/CompanyWorkFlow/Create.cshtml
@model BCR.Bio.Domain.NV.CompanyWorkFlow

@{
    ViewBag.Title = "Crear WorkFlow";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    @using (Html.BeginForm("Create", "CompanyWorkFlow", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="card">
            <h5 class="card-header text-white">Ingrese los Datos</h5>
            <div class="card-body">
                @Html.Partial("_Fields", Model)
            </div>

            <div class="card-footer">

                <button type="submit" class="btn btn-primary ">
                    <i class="fa fa-floppy-o"></i> Guardar
                </button>
                <a href="@Url.Action("index")" class="btn btn-warning  ">
                    <i class="fa fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    }

</div>

@section Scripts
{
    <script type="text/javascript">

        $.validator.methods.range = function (value, element, param) {
            var globalizedValue = value.replace(",", ".");
            return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
        }


        $.validator.methods.number = function (value, element) {
            return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
        }

    </script>
}

Biometrika.Manager.CI/Biometrika.Manager.CI/Views/CompanyWorkFlow/Edit.cshtml
@model BCR.Bio.Domain.NV.CompanyWorkFlow

@{
    ViewBag.Title = "Editar WorkFlow";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    @using (Html.BeginForm("Edit", "CompanyWorkFlow", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="card">
            <h5 class="card-header text-white">Ingrese los Datos</h5>
            <div class="card-body">
                @Html.Partial("_Fields", Model)
            </div>

            <div class="card-footer">

                <button type="submit" class="btn btn-primary ">
                    <i class="fa fa-floppy-o"></i> Guardar
                </button>
                <a href="@Url.Action("index")" class="btn btn-warning  ">
                    <i class="fa fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    }

</div>

@section Scripts
{
    <script type="text/javascript">

        $.validator.methods.range = function (value, element, param) {
            var globalizedValue = value.replace(",", ".");
            return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
        }


        $.validator.methods.number = function (value, element) {
            return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
        }

    </script>
}

Biometrika.Manager.CI/Biometrika.Manager.CI/Views/CompanyWorkFlow/Index.cshtml
@model IList<BCR.Bio.Domain.NV.CompanyWorkFlow>
@{
    ViewBag.Title = "WorkFlows";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>

    input {
        display: block;
        width: 100%;
        padding: .375rem .75rem;
        font-size: 1rem;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: .25rem;
        transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    }
</style>

<div class="container">

    <div class="card">

        <h5 class="card-header text-white">Company WorkFlows</h5>


        <div class="card-body">
            <a class="btn btn-primary mb-2" href="@Url.Action("Create")">
                <i class="fa fa-plus-circle"></i> Crear
            </a>
            <table cellpadding="1" cellspacing="1" class="table table-bordered table-responsive-sm table-striped text-center" style="font-size:12px;">
                <tr>
                    <th class="col-1 text-center">Compañía</th>
                    <th class="col-1 text-center">Nombre</th>
                    <th class="col-1 text-center">OnBoardingMandatory</th>
                    <th class="col-2 text-center">TypeOB</th>
                    <th class="col-2 text-center">TypeVerify</th>
                    <th class="col-1 text-center">Umbral</th>
                    <th class="col-4 text-center">Acciones</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Company.Name
                        </td>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.OnBoardingMandatory
                        </td>
                        <td>
                            @item.BpWebTypeOnBoarding
                        </td>
                        <td>
                            @item.BpWebTypeVerify
                        </td>
                        <td>
                            @item.Threshold
                        </td>
                        <td>
                            <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-sm btn-warning my-1">
                                <i class="fa fa-pencil"></i> Editar
                            </a>
                            <a href="@Url.Action("Clone", new { id = item.Id })" class="btn btn-sm btn-success my-1">
                                <i class="fa fa-clone"></i> Duplicar
                            </a>
                            <button type="button" onclick="deleteCompanyWorkFlow(@item.Id)" class="btn btn-sm btn-danger my-1">
                                <i class="fa fa-trash-o"></i> Eliminar
                            </button>
                        </td>

                    </tr>
                }
            </table>
        </div>
        <div class="card-footer">

        </div>

    </div>


</div>
@section Scripts
{
    <script type="text/javascript">

        function deleteCompanyWorkFlow(id) {
            const url = '@Url.Action("Delete","CompanyWorkFlow")';
            const confirmation = confirm("¿Está seguro que desea eliminar? Esta acción no se puede deshacer.");
            if (!confirmation) return;

            $.ajax({
                type: 'GET',
                url: url,
                data: { 'id': id },
                success: function (response) {
                    if (response && response.res === true) {
                        alert('Eliminado correctamente')
                        location.reload();
                    } else {
                        alert("Error al eliminar. Favor revisar log o contactar a soporte.");
                    }
                },
                error: function (error) {
                    console.debug(error);
                }
            })
        }

    </script>
}

Biometrika.Manager.CI/Biometrika.Manager.CI/Views/CompanyWorkFlow/_Fields.cshtml
@model BCR.Bio.Domain.NV.CompanyWorkFlow

<div class="form-group">
    @Html.Label("Company")
    <div class="col-xs-4">
        @*@Html.DropDownList("CompanyId", new SelectList(ViewBag.CompanySelectList, "Value", "Text"), new { @class = "form-control" })*@
        @Html.DropDownList("CompanySelectList", null, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Name, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EditorFor(m => m.Name, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.OnBoardingMandatory, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EnumDropDownListFor(m => m.OnBoardingMandatory, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.BpWebTypeOnBoarding, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EnumDropDownListFor(x => x.BpWebTypeOnBoarding, null, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.BpWebTypeVerify, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EnumDropDownListFor(x => x.BpWebTypeVerify, null, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.ReceiverList, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EditorFor(m => m.ReceiverList, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Threshold, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EditorFor(m => m.Threshold, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Theme, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EditorFor(m => m.Theme, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.RedirectUrl, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EditorFor(m => m.RedirectUrl, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.GeoRefMandatory, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EnumDropDownListFor(m => m.GeoRefMandatory, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Authorization, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EnumDropDownListFor(m => m.Authorization, new { @class = "form-control" })
    </div>
</div>
@*<div class="form-group">
        @Html.LabelFor(m => m.AuthorizationMessage, new { @class = "control-label" })
        <div class="col-xs-4">
            @Html.TextAreaFor(m => m.AuthorizationMessage, new { @class = "form-control" })
        </div>
    </div>*@

<div class="form-group">
    @Html.Label("Título Authorization Message", new { @class = "control-label" })
    @Html.TextBox("AuthorizationMessageTitle")
</div>
<div class="form-group">
    @Html.Label("Cuerpo Authorization Message", new { @class = "control-label" })
    @Html.TextArea("AuthorizationMessageBody", new { @class = "form-control" })
</div>
<div class="form-group">
    @Html.Label("Pie Authorization Message", new { @class = "control-label" })
    @Html.TextArea("AuthorizationMessageFooter", new { @class = "form-control" })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.SignerInclude, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EnumDropDownListFor(m => m.SignerInclude, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.CheckLockSrcei, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EnumDropDownListFor(m => m.CheckLockSrcei, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.VideoInclude, new { @class = "control-label" })
    <div class="col-xs-4">
        @Html.EnumDropDownListFor(m => m.VideoInclude, new { @class = "form-control" })
    </div>
</div>

<div class="form-group">
    @Html.Label("Video Message", new { @class = "control-label" })
    @Html.TextAreaFor(m => m.VideoMessage, new { @class = "form-control" })
</div>


@*<div class="form-group">
        @Html.LabelFor(m => m.VideoMessage, new { @class = "control-label" })
        <div class="col-xs-4">
            @Html.TextAreaFor(m => m.VideoMessage, new { @class = "form-control" })
        </div>
    </div>*@