Biometrika.Manager.CI/Biometrika.Manager.CI/Controllers/CompanyController.cs
using AutoMapper;
using BCR.Bio.Domain;
using BCR.Bio.Domain.NV;
using BCR.Bio.Domain.Interface;
using BCR.System.Log;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebNV.Models.Admin;

namespace WebNV.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [Authorize(Roles = ("Super Admin,Administrador"))]
    public class CompanyController : BaseController
    {
        //
        // GET: /Company/
        [Authorize(Roles = ("Super Admin"))]
        public ActionResult Index(string RutToSearch, string RazonSocialToSearch, int? EstadoToSearch)
        {

            if (!string.IsNullOrEmpty(RazonSocialToSearch))
                RazonSocialToSearch = RazonSocialToSearch.Trim();
            if (!string.IsNullOrEmpty(RutToSearch))
                RutToSearch = RutToSearch.Trim();

            //Paginacion paginacion = new Paginacion() { Cantidad = 10, Pagina = id ?? 0 };
            List<BpCompanyModel> bpCompanyModelList = new List<BpCompanyModel>();

            if (CurrentUser.Companies.Count > 0)
            {
                int holdingId = UoW.GetHolding(User.Identity.Name);

                IList<ICompany> companylist;
                if (EstadoToSearch == null)
                    companylist = UoW.CompanyService.GetByRutAndName(RutToSearch ?? "", RazonSocialToSearch ?? "", holdingId);
                else
                    companylist = UoW.CompanyService.GetByRutAndStatusAndName(RutToSearch ?? "", (int)EstadoToSearch, RazonSocialToSearch ?? "", holdingId);


                companylist
                    .ToList()
                    .ForEach(m => bpCompanyModelList.Add(Transform(m)));
            }
            return View(bpCompanyModelList);
        }

        private BpCompanyModel Transform(ICompany m)
        {
            BpCompanyModel cm = new BpCompanyModel();
            cm.Id = m.Id;
            cm.Rut = m.Rut;
            cm.Address = m.Address;
            cm.Name = m.Name;
            cm.Domain = m.Domain;
            cm.Phone = m.Phone;
            cm.CreateDate = m.CreateDate;
            cm.Status = m.Status;
            cm.EndDate = m.EndDate;

            return cm;
        }


        [Authorize(Roles = ("Administrador"))]
        public ActionResult Info()
        {
            BpCompanyModel bpCompanyModel = Mapper.Map<Company, BpCompanyModel>((Company)UoW.CompanyService.GetById(CurrentUserCompany.Id, withHQs: true, withSectors: true));
            return View(bpCompanyModel);
        }

        /// <summary>
        /// Edita la comapñia, get
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = ("Super Admin"))]
        public ActionResult Edit(int id)
        {
            BpCompanyModel bpCompanyModel = Mapper.Map<Company, BpCompanyModel>((Company)UoW.CompanyService.GetById(id, withHQs: true, withSectors: true));
            bpCompanyModel.Status = bpCompanyModel.EndDate == null;
            bpCompanyModel.HoldingList = Helpers.Web.HoldingList(UoW.HoldingService.List(), bpCompanyModel.Holding.ToString());


            return View(bpCompanyModel);
        }

        /// <summary>
        /// Edita la compañia , post
        /// </summary>
        /// <param name="bpCompanyModel"></param>
        /// <returns></returns>
        [Authorize(Roles = ("Super Admin"))]
        [HttpPost]
        public ActionResult Edit(BpCompanyModel bpCompanyModel)
        {
            try
            {
                ICompany company = UoW.CompanyService.GetById(bpCompanyModel.Id);
                company.UpdateDate = DateTime.Now;
                company.Address = bpCompanyModel.Address;
                company.ContactName = bpCompanyModel.ContactName;
                company.Domain = bpCompanyModel.Domain;
                company.Fax = bpCompanyModel.Fax;
                //company.Holding = bpCompanyModel.Holding;
                company.Name = bpCompanyModel.Name;
                company.Phone = bpCompanyModel.Phone;
                company.Phone2 = bpCompanyModel.Phone2;
                company.Rut = bpCompanyModel.Rut;
                if (company.Status != bpCompanyModel.Status)
                {
                    if (!bpCompanyModel.Status)
                    {
                        company.EndDate = DateTime.Now;
                        company.Status = false;
                    }

                    else
                    {
                        company.EndDate = null;
                        company.Status = true;
                    }
                }


                Company bpCompany = (Company)UoW.CompanyService.Update(company);


                if (!ModelState.IsValid)
                {
                    bpCompanyModel.HoldingList = Helpers.Web.HoldingList(UoW.HoldingService.List(), bpCompanyModel.Holding.ToString());
                    return View(bpCompanyModel);
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Log4Bio.Error("Error al actualizar una empresa", e);
                bpCompanyModel.HoldingList = Helpers.Web.HoldingList(UoW.HoldingService.List(), bpCompanyModel.Holding.ToString());
                return View(bpCompanyModel);
            }
        }

        /// <summary>
        /// Crea la compañia , Get
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = ("Super Admin"))]
        public ActionResult Create()
        {
            BpCompanyModel bpCompanyModel = new BpCompanyModel();
            bpCompanyModel.HoldingList = Helpers.Web.HoldingList(UoW.HoldingService.List(), bpCompanyModel.Holding.ToString());
            bpCompanyModel.Status = true;
            return View(bpCompanyModel);
        }

        /// <summary>
        /// Crea la compañia , post
        /// </summary>
        /// <param name="bpCompanyModel"></param>
        /// <returns></returns>
        [Authorize(Roles = ("Super Admin"))]
        [HttpPost]
        public ActionResult Create(BpCompanyModel bpCompanyModel)
        {

            try
            {
                Company bpCompany = UoW.CreateCompany(Mapper.Map<BpCompanyModel, Company>(bpCompanyModel));


                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "Error interno ");
                    return View(bpCompanyModel);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = ("Super Admin"))]
        public ActionResult Disable(int id)
        {
            UoW.CompanyService.Disable(id);
            return RedirectToAction("Index");
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = ("Super Admin"))]
        public ActionResult Enable(int id)
        {
            UoW.CompanyService.Enable(id);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = ("Super Admin"))]
        public ActionResult DisableHQ(int id, string back)
        {
            UoW.HQService.Disable(id);
            return Redirect(back);
        }

        [Authorize(Roles = ("Super Admin"))]
        public ActionResult EnableHQ(int id, string back)
        {
            UoW.HQService.Enable(id);
            return Redirect(back);
        }

        [Authorize(Roles = ("Super Admin"))]
        public ActionResult DisableSector(int id, string back)
        {
            UoW.SectorService.Disable(id);
            return Redirect(back);
        }
        [Authorize(Roles = ("Super Admin"))]
        public ActionResult EnableSector(int id, string back)
        {
            UoW.SectorService.Enable(id);
            return Redirect(back);
        }

        /// <summary>
        /// Elimina la compañia, GET de la page
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = ("Super Admin"))]
        public ActionResult Delete(int id)
        {
            return View(Mapper.Map<Company, BpCompanyModel>((Company)UoW.CompanyService.GetById(id)));
        }

        /// <summary>
        /// Elimina la ocmpañia, post
        /// </summary>
        /// <param name="bpCompanyModel"></param>
        /// <returns></returns>
        [Authorize(Roles = ("Super Admin"))]
        [HttpPost]
        public ActionResult Delete(BpCompanyModel bpCompanyModel)
        {
            try
            {
                /// Limpia el Model State de validaciones innecesarias
                ModelState.Clear();

                UoW.CompanyService.Delete<Company>(bpCompanyModel.Id);

                if (!ModelState.IsValid)
                    return View(bpCompanyModel);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #region HQ

        /// <summary>
        ///
        /// </summary>
        /// <param name="company"></param>
        /// <param name="back"></param>
        /// <returns></returns>
        public ActionResult AddHQ(int company, string back)
        {
            //UoW.TownService.List()

            ICompany companyObj = UoW.CompanyService.GetById(company);
            HQModel HQModel = new HQModel();
            HQModel.CompanyId = companyObj.Id;
            HQModel.CompanyName = companyObj.Name;
            HQModel.Countries = UoW.CountryService.List().ToList();
            HQModel.Back = back;
            return View(HQModel);
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="HQModel"></param>
        /// <returns></returns>

Biometrika.Manager.CI/Biometrika.Manager.CI/Views/Company/AddHQ.cshtml
@model WebNV.Models.Admin.HQModel

@{
    ViewBag.Title = "Agregar Sede";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddHQ", "Company", FormMethod.Post, new { name = "formid", Id = "formid", @class = "form-horizontal" }))
{
    <div class="hpanel">
        <div class="panel-heading hbuilt ">
            Agregando Sede
        </div>
        <div class="panel-body">

            @Html.Partial("_FieldsHQ", Model)
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-default">
                <i class="fa fa-floppy-o"></i>
                Agregar Sede
            </button>
            <a class="btn btn-default " href="@Model.Back">
                <i class="fa fa-times"></i>Cancelar
            </a>
            @Html.ValidationSummary(false, "Error en el ingreso.")
        </div>
    </div>
}

Biometrika.Manager.CI/Biometrika.Manager.CI/Views/Company/AddSector.cshtml
@model WebNV.Models.Admin.SectorModel

@{
    ViewBag.Title = "Agregar Sector";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddSector", "Company", FormMethod.Post, new { name = "formid", Id = "formid", @class = "form-horizontal" }))
{
    <div class="hpanel">
        <div class="panel-heading hbuilt ">
            Agregando Sector
        </div>
        <div class="panel-body">

            <div class="form-group">
                <div class="row">
                    @Html.LabelFor(m => m.CompanyName, new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(m => m.CompanyName, new { @readonly = "readonly", @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    @Html.LabelFor(m => m.Id, new { @class = "col-sm-2 control-label" })
                    <div class="col-xs-4">
                        @Html.TextBoxFor(m => m.Id, new { @readonly = "readonly", @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    @Html.LabelFor(m => m.Description, new { @class = "col-sm-2 control-label" })
                    <div class="col-xs-4">
                        @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    @Html.LabelFor(m => m.ContactName, new { @class = "col-sm-2 control-label" })
                    <div class="col-xs-4">
                        @Html.TextBoxFor(m => m.ContactName, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            @Html.HiddenFor(m => m.CompanyId)
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-default">
                <i class="fa fa-floppy-o"></i>
                Agregar Sector
            </button>
            <a class="btn btn-default " href="@Model.Back">
                <i class="fa fa-times"></i>Volver
            </a>
            @Html.ValidationSummary(false, "Error en el ingreso.")
        </div>
    </div>
}

Biometrika.Manager.CI/Biometrika.Manager.CI/Views/Company/Create.cshtml
@model WebNV.Models.Admin.BpCompanyModel

@{
    ViewBag.Title = "Crear Compañia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    @using (Html.BeginForm("Create", "Company", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="card">
            <h5 class="card-header text-white">Ingrese los Datos</h5>
            <div class="card-body">
                @Html.Partial("_Fields", Model)
            </div>

            <div class="card-footer">

                <button type="submit" class="btn btn-primary ">
                    <i class="fa fa-floppy-o"></i> Crear Empresa
                </button>
                <a href="@Url.Action("index")" class="btn btn-warning  ">
                    <i class="fa fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    }
</div>

Biometrika.Manager.CI/Biometrika.Manager.CI/Views/Company/Delete.cshtml
@model WebNV.Models.Admin.BpCompanyModel

@using (Html.BeginForm("Delete", "Company", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="hpanel">
        <div class="panel-heading hbuilt">
            Confirmar borrado
        </div>
        <div class="panel-body">

            <div class="form-group">
                @Html.LabelFor(m => m.Rut, new { @class = "col-sm-2 control-label" })
                <div class="col-xs-4">
                    @Html.TextBoxFor(m => m.Rut, new { @class = "form-control", @readonly = "readonly" })
                   
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
                <div class="col-xs-4">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @readonly = "readonly" })
                    
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Domain, new { @class = "col-sm-2 control-label" })
                <div class="col-xs-4">
                    @Html.TextBoxFor(m => m.Domain, new { @class = "form-control", @readonly = "readonly" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Address, new { @class = "col-sm-2 control-label" })
                <div class="col-xs-4">
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control", @readonly = "readonly" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Phone, new { @class = "col-sm-2 control-label" })
                <div class="col-xs-4">
                    @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", @readonly = "readonly" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Phone2, new { @class = "col-sm-2 control-label" })
                <div class="col-xs-4">
                    @Html.TextBoxFor(m => m.Phone2, new { @class = "form-control", @readonly = "readonly" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Fax, new { @class = "col-sm-2 control-label" })
                <div class="col-xs-4">
                    @Html.TextBoxFor(m => m.Fax, new { @class = "form-control", @readonly = "readonly" })


                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.ContactName, new { @class = "col-sm-2 control-label" })
                <div class="col-xs-4">
                    @Html.TextBoxFor(m => m.ContactName, new { @class = "form-control", @readonly = "readonly" })
                        
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Status, new { @class = "col-sm-2 control-label" })
                <div class="col-xs-4">
                     
                    @Html.DisplayFor(m => m.Status,new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn  btn-default ">
                <i class="fa fa-trash"></i> Eliminar
            </button>
            <a href="@Url.Action("index")" class="btn    btn-default  ">
                <i class="fa fa-times"></i> Cancelar
            </a>
        </div>
    </div>
}

Biometrika.Manager.CI/Biometrika.Manager.CI/Views/Company/Edit.cshtml
@model WebNV.Models.Admin.BpCompanyModel

@{
    ViewBag.Title = "Editar Compañia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    @using (Html.BeginForm("Edit", "Company", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="card">
            <h5 class="card-header text-white">Ingrese los Datos</h5>
            <div class="card-body">
                @Html.Partial("_Fields", Model)
            </div>

            <div class="card-footer">

                <button type="submit" class="btn btn-primary ">
                    <i class="fa fa-floppy-o"></i> Guardar
                </button>
                <a href="@Url.Action("index")" class="btn btn-warning  ">
                    <i class="fa fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    }

    <div class="card">
        <ul class="nav nav-tabs card-header text-white">
            <li class="active"><button class="btn btn-sm btn-info" data-toggle="tab" href="#tab-1" aria-expanded="true"><i class="fa fa-sitemap"></i>-Sedes</button></li>
            <li class=""><button class="btn btn-sm btn-info" data-toggle="tab" href="#tab-2" aria-expanded="false"><i class="fa fa-bookmark-o"></i>-Sectores</button></li>
        </ul>
        <div class="card-body">
            <div class="tab-content">
                <div id="tab-1" class="tab-pane active">
                    @if (Model.HQs != null)
                    {
                        <div class="panel-heading hbuilt ">
                            Sedes
                            <div class="btn-group pull-right">
                                @if (Model.EndDate == null)
                                {
                                    <a href="@Url.Action("AddHQ", new { company = @Model.Id, back = @Request.Url.ToString() })" class="btn btn-sm btn-toolbar btn-default">
                                        <i class="fa fa-plus-circle"></i> Agregar Sede
                                    </a>
                                }
                                else
                                {
                                    <a class="btn btn-sm btn-default disabled ">
                                        <i class="fa fa-plus-circle"></i> Agregar Sede
                                    </a>
                                }
                            </div>
                        </div>
                        <div class="panel-body">
                            <table cellpadding="1" cellspacing="1" class="table table-bordered table-responsive-sm table-striped text-center" id="tablaInfo">
                                <thead>
                                    <tr>

                                        <th>#</th>
                                        <th>Descripción</th>
                                        <th>Dirección</th>
                                        <th>Contacto</th>
                                        <th>Teléfono</th>
                                        <th>Barrio</th>
                                        <th>Fin</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.HQs)
                                    {
                                        var isDisabled = "";
                                        if (item.EndDate != null)
                                        {
                                            isDisabled = "class='danger'";
                                        }
                                        <tr @Html.Raw(isDisabled)>

                                            <td>@item.Id</td>
                                            <td>@item.Description</td>
                                            <td>@item.Address</td>
                                            <td>@item.Contact</td>
                                            <td>@item.Phone</td>
                                            <td>
                                                @if (item.Town != null)
                                                {
                                                    @item.Town.Description
                                                }
                                            </td>
                                            <td>
                                                @item.EndDate
                                            </td>
                                            <td>
                                                <a href="@Url.Action("EditHQ", new { company = @Model.Id, hqId=item.Id ,back = @Request.Url.ToString() })" class="btn  btn-sm   btn-default ">
                                                    <i class="fa fa-pencil"></i> Editar
                                                </a>
                                                @*<a href="#" class="btn btn-default" onclick="DeleteSede(@item.Id)">
                                                        <i class="fa fa-trash"></i> Eliminar
                                                    </a>*@
                                                @if (item.EndDate == null)
                                                {
                                                    <a href="@Url.Action("DisableHQ", new { id = item.Id ,back = @Request.Url.ToString()})" class="btn  btn-sm btn-default ">
                                                        <i class="fa fa-toggle-off"></i> Deshabilitar
                                                    </a>
                                                }
                                                else
                                                {

                                                    if ((item.Company.EndDate == null))
                                                    {
                                                        <a href="@Url.Action("EnableHQ", new { id = item.Id ,back = @Request.Url.ToString()})" class="btn  btn-sm btn-default ">
                                                            <i class="fa fa-toggle-on"></i> Habilitar
                                                        </a>
                                                    }
                                                    else
                                                    {
                                                        <a class="btn  btn-sm  btn-default disabled" title="Compañia no habilitado.">
                                                            <i class="fa fa-toggle-on"></i> Habilitar
                                                        </a>
                                                        <i class="fa fa-comment" rel="tooltip" id="blah" title="Compañia no habilitado."></i>
                                                    }

                                                }
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    }
                </div>

                <div id="tab-2" class="tab-pane">
                    @if (Model.Sectors != null)
                    {
                        <div class="panel-heading hbuilt ">
                            Sectores
                            <div class="btn-group pull-right">
                                @if (Model.EndDate == null)
                                {
                                    <a href="@Url.Action("AddSector", new { company = @Model.Id, back = @Request.Url.ToString() })" class="btn btn-sm  btn-default ">
                                        <i class="fa fa-plus-circle"></i> Agregar Sector
                                    </a>
                                }
                                else
                                {
                                    <a class="btn btn-sm btn-default disabled">
                                        <i class="fa fa-plus-circle"></i> Agregar Sector
                                    </a>
                                }
                            </div>
                        </div>
                        <div class="panel-body">
                            <table cellpadding="1" cellspacing="1" class="table table-bordered table-responsive-sm table-striped text-center" id="tablaInfo">
                                <thead>
                                    <tr>

                                        <th>#</th>
                                        <th>Descripción</th>
                                        <th>Puntos</th>
                                        <th>Fin</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Sectors)
                                    {
                                        var isDisabled = "";
                                        if (item.EndDate != null)
                                        {
                                            isDisabled = "class='danger'";
                                        }
                                        <tr @Html.Raw(isDisabled)>

                                            <td>@item.Id</td>
                                            <td>@item.Description</td>
                                            <td>
                                                @if (item.Points != null)
                                                {
                                                    <a>link</a>
                                                }
                                            </td>
                                            <td>@item.EndDate</td>
                                            <td>
                                                <a href="@Url.Action("EditSector", new { company = @Model.Id, sectorId=item.Id ,back = @Request.Url.ToString() })" class="btn  btn-sm  btn-default">
                                                    <i class="fa fa-pencil"></i> Editar
                                                </a>
                                                @*<a href="#" class="btn btn-default" onclick="DeleteSector(@item.Id)">
                                                        <i class="fa fa-trash"></i> Eliminar
                                                    </a>*@
                                                @if (!item.IsDisable)
                                                {
                                                    <a href="@Url.Action("DisableSector", new { id = item.Id ,back = @Request.Url.ToString()})" class="btn  btn-sm  btn-default  ">
                                                        <i class="fa fa-toggle-off"></i> Deshabilitar
                                                    </a>
                                                }
                                                else
                                                {

                                                    if (!Model.IsActive)
                                                    {
                                                        <a href="@Url.Action("EnableSector", new { id = item.Id ,back = @Request.Url.ToString()})" class="btn  btn-sm  btn-default  ">
                                                            <i class="fa fa-toggle-on"></i> Habilitar
                                                        </a>
                                                    }
                                                    else
                                                    {
                                                        <a class="btn  btn-sm  btn-default disabled" title="Compañia no habilitado.">
                                                            <i class="fa fa-toggle-on"></i> Habilitar
                                                        </a>
                                                        <i class="fa fa-comment" rel="tooltip" id="blah" title="Compañia no habilitado."></i>
                                                    }

                                                }
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

</div>